import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { CircuitBreaker, MemoryAuditSink, createSovereigntyApp, route, validateRegistries, type Registries } from '../index.js';
async function call(app: any, method: string, path: string, token?: string, body?: unknown) { const server = await new Promise<any>(resolve => { const s = app.listen(0, '127.0.0.1', () => resolve(s)); }); try { const addr = server.address() as any; const res = await fetch(`http://127.0.0.1:${addr.port}${path}`, { method, headers: { 'content-type':'application/json', ...(token ? { authorization:`Bearer ${token}` } : {}) }, body: body ? JSON.stringify(body) : undefined }); return { status: res.status, body: await res.json() }; } finally { await new Promise<void>(resolve => server.close(()=>resolve())); } }
const future = '2099-12-31';
function base(): Registries { return { jurisdictions:[{id:'us',status:'active',countryCode:'US',restrictedDataAllowed:true,notes:'dev'}], providers:[{id:'local',status:'active',type:'local',approvedForRestricted:true,jurisdictionId:'us',health:'healthy',endpointUrl:'http://127.0.0.1',notes:'dev'},{id:'cloud',status:'active',type:'cloud',approvedForRestricted:false,jurisdictionId:'us',health:'healthy',endpointUrl:'https://example.invalid',notes:'dev'}], hardware:[{id:'hw',status:'active',providerId:'local',throughput:'unknown',notes:'dev'}], rights:[{id:'rights',status:'active',licenseStatus:'allowed',commercialUse:'allowed',redistribution:'allowed',modification:'allowed',prohibitedJurisdictions:[],reviewDate:future,evidenceUrl:'https://example.invalid/rights',notes:'dev'}], models:[{id:'local-model',status:'active',providerId:'local',rightsId:'rights',hardwareId:'hw',capabilities:['chat'],operations:['inference'],costUsd:1,latencyMs:10,notes:'dev'},{id:'cloud-model',status:'active',providerId:'cloud',rightsId:'rights',capabilities:['chat'],operations:['inference'],costUsd:0.1,latencyMs:5,notes:'dev'}] }; }
const req = { operation:'inference' as const, capability:'chat' as const, dataClassification:'public' as const, jurisdictionId:'us', commercial:true };
test('rights fail closed with explicit denial reasons', () => { for (const mutate of [ (r:Registries)=>{r.models[0].rightsId='missing'}, (r:Registries)=>{r.rights[0].reviewDate='2000-01-01'}, (r:Registries)=>{r.rights[0].commercialUse='unknown'}, (r:Registries)=>{r.rights[0].commercialUse='prohibited'}, (r:Registries)=>{r.rights[0].prohibitedJurisdictions=['us']}, (r:Registries)=>{delete (r.models[0] as any).rightsId}, (r:Registries)=>{(r.rights[0] as any).evidenceUrl=''}]) { const r=base(); r.models=r.models.slice(0,1); mutate(r); const out=route(r, req); assert.equal(out.allowed,false); assert.ok(out.denialReasons.length > 0); } });
test('restricted data rejects cloud, routes local, and denies without eligible local', () => { let r=base(); let out=route(r,{...req,dataClassification:'restricted',preferredProviderId:'cloud'}); assert.equal(out.allowed,true); assert.equal(out.providerId,'local'); assert.ok(out.trace.find(t=>t.providerId==='cloud')?.reasons.includes('restricted data rejects non-approved cloud provider')); r=base(); r.providers=r.providers.filter(p=>p.id!=='local'); r.models=r.models.filter(m=>m.providerId!=='local'); const audit=new MemoryAuditSink(); out=route(r,{...req,dataClassification:'restricted'},audit); assert.equal(out.allowed,false); assert.equal(audit.events[0].type,'denial'); });
test('cost, latency, health, fallback, and circuit policies are conservative', () => { let r=base(); assert.equal(route(r,{...req,maxCostUsd:0.05}).allowed,false); assert.equal(route(r,{...req,maxLatencyMs:1}).allowed,false); r=base(); r.rights[0].commercialUse='prohibited'; assert.equal(route(r,{...req,maxCostUsd:999}).allowed,false); r=base(); r.models[0].costUsd='unknown'; assert.equal(route(r,req).providerId,'cloud'); r=base(); r.providers[0].health='unhealthy'; assert.equal(route(r,req).providerId,'cloud'); r.providers[1].health='unhealthy'; assert.equal(route(r,req).allowed,false); r=base(); const cb=new CircuitBreaker('local'); cb.disable(); assert.equal(route(r,req,undefined,new Map([['local',cb]])).providerId,'cloud'); r.models=[{...r.models[0], id:'fallback', capabilities:['chat','deterministic_fallback'], costUsd:0.01}]; const audit=new MemoryAuditSink(); assert.equal(route(r,req,audit).fallbackUsed,true); assert.equal(audit.events[0].type,'fallback'); });
test('circuit breaker state machine persists and fails corrupt state safely', () => { const cb=new CircuitBreaker('p',2,1); cb.recordFailure(1); cb.recordFailure(2); assert.equal(cb.state,'OPEN'); assert.equal(cb.canRoute(2),false); assert.equal(cb.canRoute(5),true); assert.equal(cb.state,'HALF_OPEN'); cb.recordFailure(6); assert.equal(cb.state,'OPEN'); cb.openedAt=0; cb.canRoute(10); cb.recordSuccess(); assert.equal(cb.state,'CLOSED'); cb.disable(); assert.equal(cb.canRoute(),false); cb.quarantine(); assert.equal(cb.canRoute(),false); const dir=mkdtempSync(join(tmpdir(),'sovereignty-')); cb.reset(); cb.save(join(dir,'cb.json')); assert.equal(CircuitBreaker.load(join(dir,'cb.json')).state,'CLOSED'); writeFileSync(join(dir,'bad.json'),'{bad'); assert.equal(CircuitBreaker.load(join(dir,'bad.json')).state,'OPEN'); });
test('admin endpoints require bearer token and audit actions', async () => { process.env.SOVEREIGNTY_ADMIN_TOKEN='test-token'; const audit=new MemoryAuditSink(); const cb=new CircuitBreaker('p'); const app=createSovereigntyApp(audit,new Map([['p',cb]])); assert.equal((await call(app,'POST','/v1/circuit-breakers/p/reset')).status,401); assert.equal((await call(app,'POST','/v1/circuit-breakers/p/reset','wrong')).status,401); assert.equal((await call(app,'POST','/v1/circuit-breakers/missing/reset','test-token')).status,404); assert.equal((await call(app,'POST','/v1/circuit-breakers/p/reset','test-token',{authorization:'Bearer evil'})).status,200); assert.ok(audit.events.some(e=>e.type==='admin_action')); assert.doesNotMatch(JSON.stringify(audit.events),/test-token|evil/); });
test('registry validation catches duplicate IDs, references, status, unknown fields, expired review', () => { const r=base(); r.models.push({...r.models[0]}); (r.providers[0] as any).extra=true; r.providers[0].status='bad' as any; r.models[0].providerId='missing'; r.rights[0].reviewDate='2000-01-01'; const v=validateRegistries(r); assert.equal(v.ok,false); assert.ok(v.errors.some(e=>e.includes('duplicate'))); assert.ok(v.errors.some(e=>e.includes('unknown field'))); assert.ok(v.errors.some(e=>e.includes('invalid status'))); assert.ok(v.errors.some(e=>e.includes('missing provider'))); assert.ok(v.errors.some(e=>e.includes('expired review'))); assert.equal(v.counts.models,3); });
test('stress-test admin rejects unsupported scenarios and does not bypass policy', async () => { process.env.SOVEREIGNTY_ADMIN_TOKEN='test-token'; assert.equal((await call(createSovereigntyApp(),'POST','/v1/stress-tests/run','test-token',{scenario:'unsupported'})).status,400); const r=base(); r.providers=r.providers.filter(p=>p.id!=='local'); r.models=r.models.filter(m=>m.providerId!=='local'); assert.equal(route(r,{...req,dataClassification:'restricted',stressTest:true}).allowed,false); });
