import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { buildAjv, assertAgenticEngineering } from '../scripts/validate-agentic-engineering.mjs';
const ajv=buildAjv();
const clone=o=>JSON.parse(JSON.stringify(o));
const load=p=>JSON.parse(readFileSync(p,'utf8'));
const validTask=load('examples/agentic-engineering/task.example.yaml');
const validShift=load('examples/agentic-engineering/shift.example.yaml');
const validProof=load('examples/agentic-engineering/proof-of-behavior.example.yaml');
const validReceipt=load('examples/agentic-engineering/engineering-receipt.example.yaml');
const validate=(schema,obj)=>ajv.getSchema(`https://wiredchaos.dev/schemas/agentic-engineering/${schema}.schema.json`)(obj);
test('valid task',()=>assert.equal(validate('engineering-task',validTask),true));
test('missing task budget',()=>{const o=clone(validTask); delete o.budget; assert.equal(validate('engineering-task',o),false);});
test('valid shift',()=>assert.equal(validate('engineering-shift',validShift),true));
test('missing execution owner',()=>{const o=clone(validShift); delete o.executionOwner; assert.equal(validate('engineering-shift',o),false);});
test('valid Proof-of-Behavior',()=>assert.equal(validate('proof-of-behavior',validProof),true));
test('missing observation',()=>{const o=clone(validProof); delete o.observation; assert.equal(validate('proof-of-behavior',o),false);});
test('valid low-risk receipt',()=>{const o=clone(validReceipt); o.task.riskTier='low'; assert.equal(validate('engineering-receipt',o),true);});
test('critical receipt without human approval',()=>{const o=clone(validReceipt); o.task.riskTier='critical'; o.humanApprovals=[]; assert.equal(validate('engineering-receipt',o),false);});
test('skipped gate without reason',()=>{const o=clone(validReceipt); o.completionGates.repository_surveyed={status:'skipped'}; assert.equal(validate('engineering-receipt',o),false);});
test('not-applicable runtime gate without reason',()=>{const o=clone(validReceipt); o.completionGates.application_started={status:'not_applicable'}; assert.equal(validate('engineering-receipt',o),false);});
test('scope violation',()=>{const o=clone(validShift); o.scopeViolations=['expanded scope']; assert.equal(validate('engineering-shift',o),false);});
test('implementer self-approval on critical work',()=>{const v=ajv.getSchema('https://wiredchaos.dev/schemas/agentic-engineering/risk-policy.schema.json'); assert.equal(v({reviewRouting:{low:['deterministic_checks'],medium:['independent_implementation_review'],high:['architecture_review','security_review','domain_review'],critical:['human_approval','implementer_self_approval','reproducible_evidence','rollback_plan']}}),false);});
test('complete validator catches contracts',()=>assert.doesNotThrow(()=>assertAgenticEngineering()));
test('local repository policy attempting to weaken district policy',()=>{const v=ajv.getSchema('https://wiredchaos.dev/schemas/agentic-engineering/repository-profile.schema.json'); const p=load('examples/agentic-engineering/repository-profile.example.yaml'); p.policyInheritance.mayWeakenDistrictStandard=true; assert.equal(v(p),false);});
