import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import type { Registries } from './types.js';
const keys = ['models','providers','hardware','rights','jurisdictions'] as const;
export function loadRegistries(root = 'registry/sovereignty'): Registries { const out: any = {}; for (const k of keys) out[k] = readdirSync(join(root,k)).filter(f=>f.endsWith('.json')).map(f=>JSON.parse(readFileSync(join(root,k,f),'utf8'))); return out; }
function validUrl(s: string) { try { const u = new URL(s); return ['https:','http:'].includes(u.protocol); } catch { return false; } }
export function validateRegistries(reg: Registries, now = Date.now()): { ok:boolean; errors:string[]; counts:Record<string,number> } { const errors:string[]=[]; const counts:any={}; for (const k of keys) { counts[k]=reg[k].length; const seen = new Set<string>(); for (const rec of reg[k] as any[]) { if (!rec.id) errors.push(`${k}: missing id`); if (seen.has(rec.id)) errors.push(`${k}: duplicate id ${rec.id}`); seen.add(rec.id); } }
 const sets = Object.fromEntries(keys.map(k=>[k,new Set((reg[k] as any[]).map((r:any)=>r.id))]));
 const status = new Set(['active','disabled','mock','not_verified','development_only']); const caps = new Set(['chat','embedding','tool_plan','deterministic_fallback']); const ops = new Set(['inference','evaluation','stress_test']); const allowedKeys:any = { models:['id','status','providerId','rightsId','hardwareId','capabilities','operations','costUsd','latencyMs','notes'], providers:['id','status','type','approvedForRestricted','jurisdictionId','health','endpointUrl','notes'], hardware:['id','status','providerId','throughput','notes'], rights:['id','status','licenseStatus','commercialUse','redistribution','modification','prohibitedJurisdictions','reviewDate','evidenceUrl','notes'], jurisdictions:['id','status','countryCode','restrictedDataAllowed','notes'] };
 for (const k of keys) for (const rec of reg[k] as any[]) { for (const key of Object.keys(rec)) if (!allowedKeys[k].includes(key)) errors.push(`${k}/${rec.id}: unknown field ${key}`); if (!status.has(rec.status)) errors.push(`${k}/${rec.id}: invalid status`); }
 for (const m of reg.models) { if (!sets.providers.has(m.providerId)) errors.push(`models/${m.id}: missing provider ${m.providerId}`); if (!m.rightsId || !sets.rights.has(m.rightsId)) errors.push(`models/${m.id}: missing rights ${m.rightsId}`); if (m.hardwareId && !sets.hardware.has(m.hardwareId)) errors.push(`models/${m.id}: missing hardware ${m.hardwareId}`); for (const c of m.capabilities) if (!caps.has(c)) errors.push(`models/${m.id}: invalid capability ${c}`); for (const o of m.operations) if (!ops.has(o)) errors.push(`models/${m.id}: invalid operation ${o}`); }
 for (const p of reg.providers) { if (!sets.jurisdictions.has(p.jurisdictionId)) errors.push(`providers/${p.id}: missing jurisdiction ${p.jurisdictionId}`); if (!validUrl(p.endpointUrl)) errors.push(`providers/${p.id}: malformed URL`); }
 for (const h of reg.hardware) if (!sets.providers.has(h.providerId)) errors.push(`hardware/${h.id}: missing provider ${h.providerId}`);
 for (const r of reg.rights) { if (!validUrl(r.evidenceUrl)) errors.push(`rights/${r.id}: malformed URL`); if (!r.reviewDate || Date.parse(r.reviewDate) < now) errors.push(`rights/${r.id}: expired review date`); }
 return { ok: errors.length===0, errors, counts } }
