import type { Registries, RouteRequest, RouteResult, RouteTrace, RightsRecord } from './types.js';
import type { AuditSink } from './audit.js';
import { CircuitBreaker } from './circuitBreaker.js';
const expired = (d: string) => Number.isNaN(Date.parse(d)) || Date.parse(d) < Date.now();
function rightsReasons(r?: RightsRecord, req?: RouteRequest): string[] { const out: string[] = []; if (!r) return ['missing rights record']; if (!r.id || !r.reviewDate || !r.evidenceUrl) out.push('malformed rights record'); if (r.licenseStatus === 'unknown' || r.licenseStatus === 'not_verified') out.push('license status unknown'); if (r.licenseStatus === 'prohibited') out.push('license prohibited'); if (expired(r.reviewDate)) out.push('rights review expired'); if (req?.commercial && r.commercialUse !== 'allowed') out.push(r.commercialUse === 'prohibited' ? 'commercial use prohibited' : 'commercial permission unknown'); if (req?.requireRedistribution && r.redistribution !== 'allowed') out.push('redistribution permission not granted'); if (req?.requireModification && r.modification !== 'allowed') out.push('modification permission not granted'); if (req && r.prohibitedJurisdictions.includes(req.jurisdictionId)) out.push('jurisdiction prohibited by rights'); return out; }
export function route(reg: Registries, req: RouteRequest, audit?: AuditSink, circuits = new Map<string,CircuitBreaker>()): RouteResult { const trace: RouteTrace[] = []; const ordered = [...reg.models].sort((a,b)=> (req.preferredProviderId && a.providerId===req.preferredProviderId ? -1:0) - (req.preferredProviderId && b.providerId===req.preferredProviderId ? -1:0) || ((a.costUsd === 'unknown' || a.costUsd == null ? Number.MAX_SAFE_INTEGER : a.costUsd) - (b.costUsd === 'unknown' || b.costUsd == null ? Number.MAX_SAFE_INTEGER : b.costUsd)) || a.id.localeCompare(b.id));
  for (const m of ordered) { const reasons: string[] = []; const p = reg.providers.find(x=>x.id===m.providerId); const r = m.rightsId ? reg.rights.find(x=>x.id===m.rightsId) : undefined; const j = p ? reg.jurisdictions.find(x=>x.id===p.jurisdictionId) : undefined; const cb = circuits.get(m.providerId);
    if (!m.rightsId) reasons.push('missing model-to-rights reference'); reasons.push(...rightsReasons(r, req)); if (!p) reasons.push('missing provider'); else { if (p.health !== 'healthy') reasons.push('provider unhealthy'); if (req.dataClassification === 'restricted' && !(p.type === 'local' || p.type === 'private') && !p.approvedForRestricted) reasons.push('restricted data rejects non-approved cloud provider'); if (!j) reasons.push('missing jurisdiction reference'); else if (req.dataClassification === 'restricted' && j.restrictedDataAllowed !== true) reasons.push('jurisdiction not approved for restricted data'); }
    if (!m.capabilities.includes(req.capability)) reasons.push('capability not supported'); if (!m.operations.includes(req.operation)) reasons.push('operation not supported'); if (m.costUsd === 'unknown' || m.costUsd == null) reasons.push('unknown cost'); else if (req.maxCostUsd != null && m.costUsd > req.maxCostUsd) reasons.push('maxCostUsd exceeded'); if (m.latencyMs === 'unknown' || m.latencyMs == null) reasons.push('unknown latency'); else if (req.maxLatencyMs != null && m.latencyMs > req.maxLatencyMs) reasons.push('maxLatencyMs exceeded'); if (cb && !cb.canRoute()) reasons.push(`circuit ${cb.state.toLowerCase()} rejects traffic`);
    trace.push({ candidateId:m.id, providerId:m.providerId, accepted:reasons.length===0, reasons }); if (reasons.length===0) { const fallbackUsed = m.capabilities.includes('deterministic_fallback'); if (fallbackUsed) audit?.write({ type:'fallback', action:'route', details:{ modelId:m.id, providerId:m.providerId } }); return { allowed:true, modelId:m.id, providerId:m.providerId, trace, denialReasons:[], fallbackUsed }; }
  }
  const denialReasons = [...new Set(trace.flatMap(t=>t.reasons))]; audit?.write({ type:'denial', action:'route', details:{ denialReasons, dataClassification:req.dataClassification } }); return { allowed:false, trace, denialReasons, fallbackUsed:false };
}
