import express from 'express';
import helmet from 'helmet';
import crypto from 'node:crypto';
import { CircuitBreaker } from './circuitBreaker.js';
import type { AuditSink } from './audit.js';
import { MemoryAuditSink } from './audit.js';
export function createSovereigntyApp(audit: AuditSink = new MemoryAuditSink(), circuits = new Map<string,CircuitBreaker>()) { const app = express(); app.use(helmet()); app.use(express.json({ limit:'128kb', strict:true })); app.use((req,res,next)=>{ const id=crypto.randomUUID(); (req as any).requestId=id; res.setHeader('x-request-id', id); req.setTimeout(30_000); next(); });
 const admin = (req:any,res:any,next:any)=>{ const expected=process.env.SOVEREIGNTY_ADMIN_TOKEN; const got=String(req.headers.authorization||''); if (!expected || got !== `Bearer ${expected}`) { audit.write({ type:'admin_denial', action:req.path, requestId:req.requestId }); return res.status(401).json({ error:{ code:'unauthorized', message:'admin bearer token required', requestId:req.requestId }}); } next(); };
 app.get('/health', (_req,res)=>res.json({ ok:true, service:'sovereignty-control-plane' }));
 app.post('/v1/circuit-breakers/:id/reset', admin, (req:any,res)=>{ if (!/^[A-Za-z0-9._:-]{1,100}$/.test(req.params.id)) return res.status(400).json({ error:{ code:'bad_request', message:'invalid circuit breaker id', requestId:req.requestId }}); const cb=circuits.get(req.params.id); audit.write({ type:'admin_action', action:'circuit_breaker_reset', requestId:req.requestId, details:{ id:req.params.id, found:Boolean(cb) } }); if (!cb) return res.status(404).json({ error:{ code:'not_found', message:'unknown circuit breaker', requestId:req.requestId }}); cb.reset(); res.json({ ok:true, requestId:req.requestId }); });
 app.post('/v1/evaluations/run', admin, (req:any,res)=>{ audit.write({ type:'admin_action', action:'evaluation_run', requestId:req.requestId }); res.status(202).json({ accepted:true, requestId:req.requestId }); });
 app.post('/v1/stress-tests/run', admin, (req:any,res)=>{ const allowed=['rights_fail_closed','restricted_data']; if (req.body && Object.keys(req.body).some(k=>!['scenario'].includes(k))) return res.status(400).json({ error:{ code:'bad_request', message:'unknown field', requestId:req.requestId }}); if (!allowed.includes(req.body?.scenario)) return res.status(400).json({ error:{ code:'unsupported_scenario', message:'unsupported stress scenario', requestId:req.requestId }}); audit.write({ type:'admin_action', action:'stress_test_run', requestId:req.requestId, details:{ scenario:req.body.scenario } }); res.status(202).json({ accepted:true, requestId:req.requestId }); });
 app.use((err:any, req:any, res:any, _next:any)=>res.status(500).json({ error:{ code:'internal_error', message:'internal error', requestId:req.requestId }})); return app; }
export function start() { const host=process.env.SOVEREIGNTY_HOST || '127.0.0.1'; const port=Number(process.env.SOVEREIGNTY_PORT || 8787); const server=createSovereigntyApp().listen(port, host); process.on('SIGTERM',()=>server.close()); return server; }
